### ISSUE TITLE
对布局有什么要求吗，。我的怎么无法显示

### ISSUE THREAD

**Issue by lmdiloveu** [Dsiner/SlideLayout#2]
是因为计算高度不对吗？
![image](https://user-images.githubusercontent.com/8290718/37889252-075b5bf6-30fe-11e8-858a-2dddc6befb3f.png)

**Comment by Dsiner** [comment]
布局并没有严格要求，你的代码看起来，是没问题。
能否将xml全部代码发出来？

**Comment by Dsiner** [comment]
issues #4
