### ISSUE TITLE
RecyclerView中，布局显示不完全

### ISSUE THREAD

**Issue by Jmkery** [Dsiner/SlideLayout#4]
第一次初始化的时候没有任何的问题，但是在RecyclerView的item发生改变重新刷新适配器的时候就有部分布局显示不完全，并不是wrap_content，有一种没有完全把布局给撑开的感觉

**Comment by Dsiner** [comment]
@Jmkery 
尝试移除这个标志位先
![image](https://user-images.githubusercontent.com/13994788/50584591-6e0c3100-0eab-11e9-9721-61b9a1c2536a.png)

**Comment by Jmkery** [comment]
感谢，好像解决了问题
