### ISSUE TITLE
Activity Listening

### ISSUE THREAD

**Issue by a849173140** [Dsiner/SlideLayout#7]
Hi Master
I'm a green hand, May I have a question?
if I use your Adapter ,How can I listen butten delete or click event in Activity.
For example, I need to execute a method in an Activity when I click the delete button,I try to same way listening this item, but It dosen't work.

BR
John

**Comment by Dsiner** [comment]
1. It is not necessary to use the adapter, you can replace it with RecyclerView.Adapter
2. The button(delete etc. by findViewById(R.id.delete)) setOnClickListener, return the interface callback to the activity

**Comment by a849173140** [comment]
Hi Dsiner
Thank you for your reply!
I will try.
